//! Playback verification harness — mux REAL codec data (generated by the
//! system ffmpeg oracle into `local/verify-es/`) through every container
//! facade and write `local/verify-es/out/*` files that mpv must play.
//!
//! Run: `cargo run -p mediaway-container --example playback_verify`
//! Then: `mpv local/verify-es/out/<file>` for each.

// Verification harness: panic-on-error + print are the point. Not library code.
#![allow(
    clippy::unwrap_used,
    clippy::print_stdout,
    clippy::print_stderr,
    clippy::panic,
    clippy::expect_used,
    clippy::items_after_statements,
    clippy::let_underscore_untyped,
    clippy::cast_possible_wrap,
    clippy::cast_possible_truncation
)]

use std::fs;

use mediaway_common::Bytes;
use mediaway_common::{CodecKind, Packet, Rational, StreamInfo, VideoGeometry};
use mediaway_container::{adts, flv, mp3, mp4, ogg, ts, wav, webm};

const ES: &str = "local/verify-es";
const OUT: &str = "local/verify-es/out";

fn main() {
    fs::create_dir_all(OUT).unwrap();
    verify_mp4();
    verify_flv();
    verify_ts();
    verify_adts();
    verify_mp3();
    verify_wav();
    verify_ogg_webm();
    println!("wrote outputs to {OUT}/ — verify with mpv");
}

// --- helpers ---------------------------------------------------------------

fn read(name: &str) -> Vec<u8> {
    fs::read(format!("{ES}/{name}")).unwrap_or_else(|e| panic!("missing {ES}/{name}: {e}"))
}

fn write_out(name: &str, bytes: &[u8]) {
    fs::write(format!("{OUT}/{name}"), bytes).unwrap();
    println!("wrote {name} ({} bytes)", bytes.len());
}

/// Strip ADTS headers -> (2-byte `AudioSpecificConfig`, raw AAC frames with
/// frame boundaries preserved — one Vec per frame).
fn strip_adts(adts: &[u8]) -> (Vec<u8>, Vec<Vec<u8>>) {
    let mut frames: Vec<Vec<u8>> = Vec::new();
    let mut asc: Option<Vec<u8>> = None;
    let mut off = 0usize;
    while off + 7 <= adts.len() && adts[off] == 0xFF && adts[off + 1] & 0xF0 == 0xF0 {
        let frame_len = (((adts[off + 3] & 0x03) as usize) << 11)
            | ((adts[off + 4] as usize) << 3)
            | ((adts[off + 5] >> 5) as usize);
        if frame_len < 7 || off + frame_len > adts.len() {
            break;
        }
        let id = (adts[off + 1] >> 3) & 0x01;
        let profile = ((adts[off + 2] >> 6) & 0x03) + 1;
        let sf_index = u16::from((adts[off + 2] >> 2) & 0x0F);
        let chan = ((adts[off + 2] & 0x01) << 2) | (adts[off + 3] >> 6);
        if id == 0 {
            asc.get_or_insert_with(|| {
                vec![
                    ((u16::from(profile) << 3) | (sf_index >> 1)) as u8,
                    (((sf_index & 1) << 7) | (u16::from(chan) << 3)) as u8,
                ]
            });
        }
        frames.push(adts[off + 7..off + frame_len].to_vec());
        off += frame_len;
    }
    (asc.unwrap_or_else(|| vec![0x11, 0x90]), frames)
}

/// avcC (`AVCDecoderConfigurationRecord`) extracted from an annex-B stream.
fn avcc_from_annex_b(annex_b: &[u8]) -> Bytes {
    iso_bmff::bitstream::avc::to_avcc(annex_b)
        .avcc
        .unwrap_or_else(|| Bytes::from_static(&[1, 0x42, 0, 0x1e, 0xff, 0xe1, 0, 1, 0, 0]))
}

/// Split annex-B into access units: non-VCL (SPS/PPS/SEI) prefix + VCLs until
/// the next VCL boundary.
fn annex_b_aus(annex_b: &[u8]) -> Vec<Vec<u8>> {
    let mut nals: Vec<Vec<u8>> = Vec::new();
    let mut i = 0usize;
    while i < annex_b.len() {
        let code = if annex_b[i..].starts_with(&[0, 0, 0, 1]) {
            4
        } else if annex_b[i..].starts_with(&[0, 0, 1]) {
            3
        } else {
            i += 1;
            continue;
        };
        let start = i + code;
        let mut j = start;
        while j < annex_b.len() {
            if annex_b[j..].starts_with(&[0, 0, 0, 1]) || annex_b[j..].starts_with(&[0, 0, 1]) {
                break;
            }
            j += 1;
        }
        if j > start {
            nals.push(annex_b[start..j].to_vec());
        }
        i = j;
    }
    let mut aus: Vec<Vec<u8>> = Vec::new();
    let mut cur: Vec<u8> = Vec::new();
    let mut cur_has_vcl = false;
    for nal in nals {
        let t = nal[0] & 0x1f;
        let is_vcl = (1..=5).contains(&t);
        if is_vcl && cur_has_vcl {
            aus.push(std::mem::take(&mut cur));
            cur_has_vcl = false;
        }
        cur.extend_from_slice(&[0, 0, 0, 1]);
        cur.extend_from_slice(&nal);
        cur_has_vcl |= is_vcl;
    }
    if !cur.is_empty() {
        aus.push(cur);
    }
    aus
}

const fn video_stream(codec: CodecKind, w: u32, h: u32, extra: Bytes) -> StreamInfo {
    StreamInfo::Video {
        id: 1,
        codec,
        time_base: Rational::new(1, 30),
        geometry: VideoGeometry {
            width: w,
            height: h,
        },
        extra_data: extra,
    }
}

fn audio_stream(codec: CodecKind, rate: u32, channels: u8, extra: Bytes) -> StreamInfo {
    StreamInfo::Audio {
        id: 2,
        codec,
        time_base: Rational::new(1, u32::max(rate, 1)),
        extra_data: extra,
        sample_rate: rate,
        channels: u16::from(channels),
    }
}

fn pkt(stream_id: u32, pts: i64, key: bool, payload: &[u8]) -> Packet {
    Packet {
        stream_id,
        pts,
        dts: pts,
        duration: 0,
        is_keyframe: key,
        is_discard: false,
        payload: Bytes::copy_from_slice(payload),
    }
}

// --- format verifiers ------------------------------------------------------

fn verify_mp4() {
    let h264 = read("es.h264");
    let (asc, aac) = strip_adts(&read("es.aac"));
    let avcc = avcc_from_annex_b(&h264);
    let mut m = mp4::Muxer::new();
    let v = m
        .add_track(video_stream(CodecKind::H264, 320, 240, avcc))
        .unwrap();
    let a = m
        .add_track(audio_stream(CodecKind::Aac, 48_000, 2, Bytes::from(asc)))
        .unwrap();
    let mut live = m.begin();
    for (i, au) in annex_b_aus(&h264).iter().enumerate() {
        live.push_packet(&pkt(v, i as i64, i % 30 == 0, au))
            .unwrap();
    }
    // raw AAC — one packet per frame (the facade does not split)
    for (i, frame) in aac.iter().enumerate() {
        live.push_packet(&pkt(a, i as i64, false, frame)).unwrap();
    }
    live.flush();
    let mut bytes = Vec::new();
    live.poll_bytes(&mut bytes);
    write_out("verify.mp4", &bytes);
}

fn verify_flv() {
    let h264 = read("es.h264");
    let (asc, aac) = strip_adts(&read("es.aac"));
    let mut m = flv::Muxer::new();
    m.add_track(&video_stream(
        CodecKind::H264,
        320,
        240,
        avcc_from_annex_b(&h264),
    ))
    .unwrap();
    m.add_track(&audio_stream(CodecKind::Aac, 48_000, 2, Bytes::from(asc)))
        .unwrap();
    let mut out = Vec::new();
    m.write_header(true, true, &mut out);
    for (i, au) in annex_b_aus(&h264).iter().enumerate() {
        let conv = iso_bmff::bitstream::avc::to_avcc(au);
        m.push_packet(&pkt(0, i as i64, i % 30 == 0, &conv.payload), &mut out)
            .unwrap();
    }
    for (i, frame) in aac.iter().enumerate() {
        m.push_packet(&pkt(1, i as i64, false, frame), &mut out)
            .unwrap();
    }
    write_out("verify.flv", &out);
}

fn verify_ts() {
    let h264 = read("es.h264");
    let adts = read("es.aac");
    let mut m = ts::Muxer::new(
        1,
        0x1000,
        &[
            ts::ElementaryStream {
                pid: 0x101,
                stream_type: ts::StreamType::H264,
            },
            ts::ElementaryStream {
                pid: 0x102,
                stream_type: ts::StreamType::Aac,
            },
        ],
    )
    .unwrap();
    let mut out = Vec::new();
    m.write_pat_pmt(&mut out);
    for (i, au) in annex_b_aus(&h264).iter().enumerate() {
        m.write_access_unit(
            0x101,
            au,
            (i as u64) * 3000,
            Some((i as u64) * 3000),
            i % 30 == 0,
            &mut out,
        )
        .unwrap();
    }
    // TS carries ADTS AAC (stream_type 0x0F)
    let mut off = 0usize;
    let mut p = 0u64;
    while off + 7 <= adts.len() {
        let frame_len = (((adts[off + 3] & 0x03) as usize) << 11)
            | ((adts[off + 4] as usize) << 3)
            | ((adts[off + 5] >> 5) as usize);
        if frame_len < 7 || off + frame_len > adts.len() {
            break;
        }
        m.write_access_unit(
            0x102,
            &adts[off..off + frame_len],
            p * 1024,
            Some(p * 1024),
            true,
            &mut out,
        )
        .unwrap();
        off += frame_len;
        p += 1;
    }
    write_out("verify.ts", &out);
}

fn verify_adts() {
    let (_, aac) = strip_adts(&read("es.aac"));
    let mut m = adts::Muxer::new(48_000, 2).unwrap();
    let mut out = Vec::new();
    for (i, frame) in aac.iter().enumerate() {
        m.push_packet(&pkt(1, i as i64, true, frame)).unwrap();
    }
    m.poll_bytes(&mut out);
    write_out("verify.adts.aac", &out);
}

fn verify_mp3() {
    let mp3 = read("es.mp3");
    // skip leading ID3 tag: scan for a frame sync
    let mut syn = 0usize;
    while syn + 4 <= mp3.len() && !(mp3[syn] == 0xFF && mp3[syn + 1] & 0xE0 == 0xE0) {
        syn += 1;
    }
    let mp3 = &mp3[syn..];
    // parse the first frame header (MPEG-1 Layer III, 44100 Hz stereo 128k)
    let hdr = &mp3[0..4];
    let ver = (hdr[1] >> 3) & 0x03; // 3 = MPEG1
    let layer = (hdr[1] >> 1) & 0x03; // 1 = Layer III
    assert_eq!(ver, 3, "expected MPEG-1");
    assert_eq!(layer, 1, "expected Layer III");
    const BITRATES: [u16; 15] = [
        0, 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320,
    ];
    const RATES: [u32; 3] = [44_100, 48_000, 32_000];
    let bi = ((hdr[2] >> 4) & 0x0F) as usize;
    let si = ((hdr[2] >> 2) & 0x03) as usize;
    let cm = match (hdr[3] >> 6) & 0x03 {
        0 => mpeg_audio::ChannelMode::Stereo,
        1 => mpeg_audio::ChannelMode::JointStereo,
        2 => mpeg_audio::ChannelMode::DualChannel,
        _ => mpeg_audio::ChannelMode::Mono,
    };
    let header = mpeg_audio::FrameHeader {
        version: mpeg_audio::MpegVersion::Mpeg1,
        bitrate_kbps: BITRATES[bi],
        sample_rate: RATES[si],
        channel_mode: cm,
    };
    let m = mp3::Muxer::new(header).unwrap();
    let mut out = Vec::new();
    let mut off = 0usize;
    while off + 4 <= mp3.len() {
        let b = &mp3[off..off + 4];
        if b[0] != 0xFF || b[1] & 0xE0 != 0xE0 {
            off += 1;
            continue;
        }
        let bi2 = ((b[2] >> 4) & 0x0F) as usize;
        let si2 = ((b[2] >> 2) & 0x03) as usize;
        let padding2 = (b[2] >> 1) & 0x01 == 1;
        // MPEG-1 Layer III frame length: 144000 * bitrate / samplerate
        // (includes the 4-byte header), +1 with padding.
        let frame_len =
            144_000 * usize::from(BITRATES[bi2]) / RATES[si2] as usize + usize::from(padding2);
        if off + frame_len > mp3.len() {
            break;
        }
        m.write_frame(&mp3[off + 4..off + frame_len], padding2, &mut out)
            .unwrap();
        off += frame_len;
    }
    write_out("verify.mp3", &out);
}

fn verify_wav() {
    let pcm = read("es.pcm");
    let mut m = wav::Muxer::new(48_000, 2, 16);
    m.push_packet(&pkt(1, 0, true, &pcm));
    let bytes = m.finish();
    write_out("verify.wav", &bytes);
}

fn verify_ogg_webm() {
    // Demux ffmpeg's ogg (opus) with our demuxer, then re-mux to ogg + webm.
    let mut d = ogg::Demuxer::new();
    d.push_bytes(&read("es.opus"));
    let mut packets: Vec<(u32, Packet)> = Vec::new();
    while let Some(p) = d.poll_packet() {
        packets.push((p.stream_id, p));
    }
    // streams() is populated by poll_packet; the identification header
    // (OpusHead) is consumed into the stream's extra_data.
    let streams = d.streams().to_vec();
    let head = streams
        .iter()
        .find_map(|s| match s {
            StreamInfo::Audio { extra_data, .. } if extra_data.starts_with(b"OpusHead") => {
                Some(extra_data.clone())
            }
            _ => None,
        })
        .expect("OpusHead in stream extra_data");
    // ogg needs head + comment header + audio in order; webm must NOT carry
    // OpusTags as an audio block (decoders reject it) — keep both views.
    let all: Vec<(u32, Packet)> = packets;
    let data: Vec<(u32, Packet)> = all
        .iter()
        .filter(|(_, p)| !p.payload.starts_with(b"OpusTags"))
        .cloned()
        .collect();

    // ogg re-mux: the identification header must be the first packet
    let mut mo = ogg::Muxer::new(0x4D57); // serial
    mo.push_packet(&pkt(0, 0, true, &head)).unwrap(); // identification header
    for (s, p) in &all {
        mo.push_packet(&pkt(*s, p.pts, p.is_keyframe, &p.payload))
            .unwrap();
    }
    mo.flush();
    let mut ogg_bytes = Vec::new();
    mo.poll_bytes(&mut ogg_bytes);
    write_out("verify.opus.ogg", &ogg_bytes);

    // webm (audio-only opus)
    let mut mw = webm::Muxer::<webm::Open>::new();
    let wm_id = mw
        .add_track(audio_stream(CodecKind::Opus, 48_000, 2, head))
        .unwrap();
    let mut live = mw.begin();
    for (_, p) in &data {
        live.push_packet(&pkt(wm_id, p.pts, p.is_keyframe, &p.payload))
            .unwrap();
    }
    live.flush();
    let mut webm_bytes = Vec::new();
    live.poll_bytes(&mut webm_bytes);
    write_out("verify.webm", &webm_bytes);
}
