//! End-to-end: run the built `mediaway-avprobe` binary against a small MP4
//! fixture generated in Rust (never a committed media binary).

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    reason = "integration test may unwrap"
)]

use mediaway_common::{Bytes, CodecKind, Packet, Rational, StreamInfo, VideoGeometry};
use mediaway_container::mp4::Muxer;
use mediaway_test_media::TestMediaError;
use std::path::Path;
use std::process::Command;

/// Expected BLAKE3 of the fixture generated by [`write_fixture_mp4`]. Recompute
/// with `mediaway_test_media::hash_bytes` if the generator below changes.
const FIXTURE_BLAKE3: &str = "9a7d26adc033d12c28d86b2ecbc5caed7402465b408f80438a9a759fc29d6aa7";

fn write_fixture_mp4(path: &Path) -> Result<(), TestMediaError> {
    let mut open = Muxer::new();
    let track = StreamInfo::Video {
        id: 0,
        codec: CodecKind::H264,
        time_base: Rational::new(1, 1000),
        geometry: VideoGeometry {
            width: 64,
            height: 48,
        },
        extra_data: Bytes::new(),
    };
    open.add_track(track).expect("add_track");
    let mut muxer = open.begin();

    let sps_pps_idr = Bytes::from_static(&[
        0x00, 0x00, 0x00, 0x01, 0x67, 0x42, 0x00, 0x1e, 0xab, 0x40, 0xf0, 0x28, 0xd3, 0x70, 0x00,
        0x00, 0x00, 0x01, 0x68, 0xce, 0x3c, 0x80,
    ]);
    let slice_nal = Bytes::from_static(&[
        0x00, 0x00, 0x00, 0x01, 0x65, 0xb8, 0x00, 0x04, 0x00, 0x00, 0x13, 0x88, 0x00, 0x00, 0x03,
        0x00,
    ]);

    let mut out = Vec::new();
    for i in 0..5_i64 {
        let mut payload = Vec::new();
        if i == 0 {
            payload.extend_from_slice(&sps_pps_idr);
        }
        payload.extend_from_slice(&slice_nal);
        let pts = i * 33;
        let pkt = Packet {
            stream_id: 0,
            pts,
            dts: pts,
            duration: 33,
            is_keyframe: i == 0,
            is_discard: false,
            payload: Bytes::from(payload),
        };
        muxer.push_packet(&pkt).expect("push_packet");
        muxer.poll_bytes(&mut out);
    }
    muxer.flush();
    muxer.poll_bytes(&mut out);

    std::fs::write(path, out)?;
    Ok(())
}

fn fixture_path() -> std::path::PathBuf {
    mediaway_test_media::ensure(
        "avprobe/fixture_64x48.mp4",
        FIXTURE_BLAKE3,
        write_fixture_mp4,
    )
    .expect("ensure fixture")
}

fn run_probe(args: &[&str]) -> (i32, String, String) {
    let bin = env!("CARGO_BIN_EXE_mediaway-avprobe");
    let output = Command::new(bin).args(args).output().expect("spawn probe");
    (
        output.status.code().unwrap_or(-1),
        String::from_utf8_lossy(&output.stdout).into_owned(),
        String::from_utf8_lossy(&output.stderr).into_owned(),
    )
}

#[test]
fn probes_generated_fixture_as_text() {
    let path = fixture_path();
    let (code, stdout, _stderr) = run_probe(&[path.to_str().expect("utf8 path")]);
    assert_eq!(code, 0);
    assert!(stdout.contains("[STREAM]"));
    assert!(stdout.contains("codec_name=h264"));
    assert!(stdout.contains("width=64"));
    assert!(stdout.contains("height=48"));
    assert!(stdout.contains("[FORMAT]"));
    assert!(stdout.contains("format_name=mp4"));
}

#[test]
fn probes_generated_fixture_as_json() {
    let path = fixture_path();
    let (code, stdout, _stderr) = run_probe(&[
        "-of",
        "json",
        "-show_format",
        "-show_streams",
        path.to_str().expect("utf8 path"),
    ]);
    assert_eq!(code, 0);
    assert!(stdout.contains("\"streams\""));
    assert!(stdout.contains("\"format\""));
    assert!(stdout.contains("\"codec_name\": \"h264\""));
}

#[test]
fn missing_file_exits_nonzero_without_panicking() {
    let (code, stdout, stderr) = run_probe(&["/no/such/file/should/exist.mp4"]);
    assert_eq!(code, 1);
    assert!(stdout.is_empty());
    assert!(stderr.contains("mediaway-avprobe"));
}

#[test]
fn unknown_flag_is_a_usage_error_exit_two() {
    let (code, _stdout, stderr) = run_probe(&["-bogus-flag"]);
    assert_eq!(code, 2);
    assert!(stderr.contains("-bogus-flag"));
}
